services:
  - type: web
    name: waste-material-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app2:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13